// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.user_id", "dad289b8-7601-40f2-b163-41521e74c0eb");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1546837864);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1546837984);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1546866344);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1546859384);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1546859264);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1546837744);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1546838224);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1546838104);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1546587654);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{98b97266-cfbd-463f-bd3a-c0bdcde2c4fc}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1546799400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"webcompat-reporter_mozilla_org\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1546868231040");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1546870052040");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1546866332565");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1546869932565");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181207224759");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1546837594");
user_pref("browser.slowStartup.averageTime", 10466);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20181207224759");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"feed-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1546587668383");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "6bb19d27d3434dfeaea0ca9759648867");
user_pref("extensions.blocklist.lastModified", "Wed, 02 Jan 2019 14:27:48 GMT");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1546837868);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181207224759");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{59ad3a01-f9e0-4495-b977-1dc4c6fdfdbe}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"b53a0a08-01ce-4dc2-a7f0-7a7351805c0f\",\"webcompat@mozilla.org\":\"6dd3c70b-4014-4621-94dc-de3a5422d173\",\"screenshots@mozilla.org\":\"c5364ced-3250-4e4e-9468-00396dbfe076\",\"webcompat-reporter@mozilla.org\":\"8f922d7a-6b5f-4051-8966-25eb74fc65b4\",\"fxmonitor@mozilla.org\":\"68dd00c9-4e89-4c01-83d6-1f98a9f7a4eb\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1546843001);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.benchmark.vp9.fps", 248);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1546587679);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181207224759");
user_pref("media.gmp-manager.lastCheck", 1546837536);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1546843001);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "290635c9-7788-4f4c-95ba-393e4a60217f");
user_pref("security.sandbox.plugin.tempDirSuffix", "c2f371f6-3d3c-481e-8ace-b764abe8f496");
user_pref("services.blocklist.addons.checked", 1546837943);
user_pref("services.blocklist.gfx.checked", 1546837943);
user_pref("services.blocklist.onecrl.checked", 1546837943);
user_pref("services.blocklist.pinning.checked", 1546837943);
user_pref("services.blocklist.plugins.checked", 1546837943);
user_pref("services.settings.clock_skew_seconds", -200);
user_pref("services.settings.last_update_seconds", 1546837943);
user_pref("services.settings.main.language-dictionaries.last_check", 1546837943);
user_pref("services.settings.main.onboarding.last_check", 1546837943);
user_pref("services.settings.main.sites-classification.last_check", 1546837943);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1546843001);
user_pref("toolkit.startup.last_success", 1546837593);
user_pref("toolkit.telemetry.cachedClientID", "200d4ddd-afc2-4557-a6ca-c7811985cfc2");
user_pref("toolkit.telemetry.previousBuildID", "20181207224759");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
