// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1546843445);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1546843565);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1546843325);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1546843685);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("extensions.blocklist.lastModified", "Wed, 02 Jan 2019 14:27:48 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 25);
user_pref("extensions.getAddons.cache.lastUpdate", 1546843447);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "60.2.1");
user_pref("extensions.lastPlatformVersion", "60.2.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("idle.lastDailyNotification", 1546843505);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "3cbc9f3a-6da3-4136-bd9f-a4d59e36dac");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "60.2.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1546843505);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("services.blocklist.addons.checked", 1546843535);
user_pref("services.blocklist.clock_skew_seconds", 30);
user_pref("services.blocklist.gfx.checked", 1546843535);
user_pref("services.blocklist.last_etag", "\"1546522171864\"");
user_pref("services.blocklist.last_update_seconds", 1546843535);
user_pref("services.blocklist.onecrl.checked", 1546843535);
user_pref("services.blocklist.pinning.checked", 1546843535);
user_pref("services.blocklist.plugins.checked", 1546843535);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1546843505);
user_pref("toolkit.telemetry.cachedClientID", "d8030497-5603-42f9-b63a-3a598c4ca9a1");
user_pref("toolkit.telemetry.previousBuildID", "20181011091051");
user_pref("toolkit.telemetry.prompted", 2);
